# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["main"]

jobs:
  lint:
    name: Check for syntax errors and code style
    runs-on: macos-12

    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10"
          channel: "stable"
          cache: true

      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - run: flutter pub get

      - name: Lint check
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Ensure the Dart code is formatted correctly
        run: dart format --set-exit-if-changed .
  unit-test:
    name: Unit Tests
    needs: lint
    runs-on: macos-12
    steps:
      # Set up Flutter.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10"
          channel: "stable"
          cache: true

      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Cache `pub` dependencies
        uses: actions/cache@v2
        with:
          path: $HOME/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - run: flutter pub get

      - name: Create .env file
        run: echo "" >> .env

      - name: Run unit tests
        run: flutter test --coverage
        
  build-android:
    name: Build For Android APK
    needs: unit-test
    runs-on: macos-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10"
          channel: "stable"
          cache: true
          
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
      - name: Checkout code   
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      
      - run: flutter pub get
      - run: flutter build apk
        
    
